# Generated by Django 4.0.5 on 2022-10-21 22:31

import core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50, unique=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.FileField(upload_to='videos', validators=[core.validators.file_size])),
            ],
        ),
    ]
