# Generated by Django 4.0.5 on 2022-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_videoupload_no_of_likes_videoupload_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
