# Generated by Django 4.0.5 on 2022-11-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='video_id',
            field=models.CharField(max_length=500),
        ),
    ]
